name: WordTail
version: ${project.version}
main: com.github.toylun.wordtail.WordTail
api-version: 1.15
commands:
  wtlist:
    description: WordTail リスト取得
    usage: /wtlist
  wtset:
    description: WordTail 語尾登録
    usage: /wtset [player] [word]
    default: op
  wtreset:
    description: WordTail 語尾登録リセット
    usage: /wtset [player]
    default: op